### PR TITLE
Random Style and Colour access

### PR DESCRIPTION
**Pull request by StAlRuth**
This branch contains functions that can be used to access and change the colour and style of the characters in a ```RichText::Line```, as well a corresponding interface in the ```RichText``` class itself.  It also contains an ```isolateCharacter(std::size_t)``` function in ```RichText::Line``` to accomplish the setting, and a substring function for sf::Strings in the sfe namespace. (This substring function can be replaced without too much hassle once the next version of SFML comes out with it's sf::String::substring)

The only concern I see with this setup is that the lines aren't cleaned up with adjacent strings with the same colour and style concatenated, but it would be easy to implement if the duplicate formatting data is enough of a concern.

### CODE REVIEW

**Comment by skyrpex** [comment]
@mantognini @eXpl0it3r can you guys review / merge this, please?

**Comment by eXpl0it3r** [comment]
Well the "next" version of SFML has come out, so I guess @StAlRuth should probably adapt the substring function.

**Comment by StAlRuth** [comment]
There, all instances of sfe::substring() are now sf::String::substring.  Let me know if there are any issues, I haven't found any and the function was written as a clean replacement IIRC.

**Comment by StAlRuth** [comment]
Paging @mantognini, @eXpl0it3r and @skyrpex for review so this doesn't get lost for a year again.

**Comment by skyrpex** [comment]
I merged it to develop. I'll try to install SFML and test this before merging to master.

Thanks for the PR, BTW.

**Pull request merged**
